export enum RoleName {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HR_ADMIN = 'HR_ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum PermissionKey {
  USER_CREATE = 'user:create',
  USER_READ = 'user:read',
  USER_UPDATE = 'user:update',
  USER_DISABLE = 'user:disable',

  FACE_ENROLL = 'face:enroll',
  FACE_REPLACE = 'face:replace',

  OFFICE_CREATE = 'office:create',
  OFFICE_READ = 'office:read',
  OFFICE_UPDATE = 'office:update',
  OFFICE_DISABLE = 'office:disable',

  DEPARTMENT_CREATE = 'department:create',
  DEPARTMENT_READ = 'department:read',
  DEPARTMENT_UPDATE = 'department:update',

  ATTENDANCE_CHECKIN = 'attendance:checkin',
  ATTENDANCE_CHECKOUT = 'attendance:checkout',
  ATTENDANCE_READ = 'attendance:read',
  ATTENDANCE_READ_TEAM = 'attendance:read:team',

  REPORTS_READ = 'reports:read',
  REPORTS_EXPORT = 'reports:export',

  AUDIT_READ = 'audit:read',

  ROLE_READ = 'role:read',
  ROLE_UPDATE = 'role:update',

  // Leave Management
  LEAVE_APPLY = 'leave:apply',
  LEAVE_READ_OWN = 'leave:read:own',
  LEAVE_READ_TEAM = 'leave:read:team',
  LEAVE_APPROVE = 'leave:approve',
  LEAVE_TYPE_MANAGE = 'leave:type:manage',

  // Holiday Calendar
  HOLIDAY_READ = 'holiday:read',
  HOLIDAY_MANAGE = 'holiday:manage',

  // Work Shifts & Office Hours
  SHIFT_READ = 'shift:read',
  SHIFT_MANAGE = 'shift:manage',
}

export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AUTH_METHOD_DEPRECATED = 'AUTH_METHOD_DEPRECATED',
  AUTH_METHOD_MISMATCH = 'AUTH_METHOD_MISMATCH',
  ACCOUNT_NOT_PROVISIONED = 'ACCOUNT_NOT_PROVISIONED',
  ACCOUNT_IDENTITY_MISMATCH = 'ACCOUNT_IDENTITY_MISMATCH',

  FACE_NOT_ENROLLED = 'FACE_NOT_ENROLLED',
  FACE_NOT_DETECTED = 'FACE_NOT_DETECTED',
  MULTIPLE_FACES = 'MULTIPLE_FACES',
  FACE_QUALITY_LOW = 'FACE_QUALITY_LOW',
  FACE_MISMATCH = 'FACE_MISMATCH',
  LIVENESS_FAILED = 'LIVENESS_FAILED',

  LOCATION_PERMISSION_DENIED = 'LOCATION_PERMISSION_DENIED',
  LOCATION_UNAVAILABLE = 'LOCATION_UNAVAILABLE',
  LOCATION_ACCURACY_LOW = 'LOCATION_ACCURACY_LOW',
  OUTSIDE_GEOFENCE = 'OUTSIDE_GEOFENCE',

  ALREADY_CHECKED_IN = 'ALREADY_CHECKED_IN',
  NO_ACTIVE_CHECKIN = 'NO_ACTIVE_CHECKIN',

  PERMISSION_DENIED = 'PERMISSION_DENIED',
  RATE_LIMITED = 'RATE_LIMITED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Leave Management
  LEAVE_NOT_FOUND = 'LEAVE_NOT_FOUND',
  LEAVE_BALANCE_INSUFFICIENT = 'LEAVE_BALANCE_INSUFFICIENT',
  LEAVE_DATES_OVERLAP = 'LEAVE_DATES_OVERLAP',
  LEAVE_INVALID_DATES = 'LEAVE_INVALID_DATES',
  LEAVE_ALREADY_REVIEWED = 'LEAVE_ALREADY_REVIEWED',
  LEAVE_TYPE_NOT_FOUND = 'LEAVE_TYPE_NOT_FOUND',
  LEAVE_ZERO_WORKING_DAYS = 'LEAVE_ZERO_WORKING_DAYS',
}

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  BOOTSTRAP_ADMIN_CREATED = 'BOOTSTRAP_ADMIN_CREATED',
  FIRST_LOGIN_LINKED = 'FIRST_LOGIN_LINKED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DISABLED = 'USER_DISABLED',
  ROLE_CHANGED = 'ROLE_CHANGED',

  FACE_ENROLLED = 'FACE_ENROLLED',
  FACE_REPLACED = 'FACE_REPLACED',

  OFFICE_CREATED = 'OFFICE_CREATED',
  OFFICE_UPDATED = 'OFFICE_UPDATED',
  OFFICE_DISABLED = 'OFFICE_DISABLED',
  OFFICE_DELETED = 'OFFICE_DELETED',

  ATTENDANCE_CHECKED_IN = 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_CHECKED_OUT = 'ATTENDANCE_CHECKED_OUT',
  ATTENDANCE_REJECTED = 'ATTENDANCE_REJECTED',

  // Leave Management
  LEAVE_APPLIED = 'LEAVE_APPLIED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  LEAVE_CANCELLED = 'LEAVE_CANCELLED',
  LEAVE_BALANCE_ALLOCATED = 'LEAVE_BALANCE_ALLOCATED',

  // Holiday Calendar
  HOLIDAY_CREATED = 'HOLIDAY_CREATED',
  HOLIDAY_UPDATED = 'HOLIDAY_UPDATED',
  HOLIDAY_DELETED = 'HOLIDAY_DELETED',
  WEEKLY_RULE_UPDATED = 'WEEKLY_RULE_UPDATED',

  // Work Shifts & Office Hours
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_UPDATED = 'SHIFT_UPDATED',
  SHIFT_DELETED = 'SHIFT_DELETED',
}

export enum LoginEventType {
  SUCCESS = 'SUCCESS',
  FAILED_PASSWORD = 'FAILED_PASSWORD',
  FAILED_FACE = 'FAILED_FACE',
  FAILED_LIVENESS = 'FAILED_LIVENESS',
  FAILED_GEOFENCE = 'FAILED_GEOFENCE',
  DISABLED_ACCOUNT = 'DISABLED_ACCOUNT',
  UNKNOWN_EMPLOYEE = 'UNKNOWN_EMPLOYEE',
}
